### PR TITLE
Spanish translation for YGOobile

### PR DESCRIPTION
**Pull request by VaHReX**
I just added the relevant files for the Spanish translation of the game in the following paths:
/master/mobile/assets    - I added the "es" folder with all the relevant files (cards.cdb, strings.conf, serverlist.xml)
/master/mobile/src/main/res     - I added the "values-es" folder with all the relevant files (strings.xml, arrays.xml)

### CODE REVIEW

**Comment by fallenstardust** [comment]
i see single files has some problem, actually you neednt to translate them

**Comment by VaHReX** [comment]
> i see single files has some problem, actually you neednt to translate them

What are the files that I have left to translate? to get to work on them as soon as possible

**Comment by mercury233** [comment]
> > i see single files has some problem, actually you neednt to translate them
> 
> What are the files that I have left to translate? to get to work on them as soon as possible

He means the puzzle lua files in the folder named "single" have problem.

As I can see, the format of those files you committed are wrong.

**Comment by VaHReX** [comment]
> > > i see single files has some problem, actually you neednt to translate them
> > 
> > 
> > What are the files that I have left to translate? to get to work on them as soon as possible
> 
> He means the puzzle lua files in the folder named "single" have problem.
> 
> As I can see, the format of those files you committed are wrong.

In that case, I did not create any, I used the same ones found within the single folder of the English language

**Comment by fallenstardust** [comment]
in this repository, you needn't upload cards.cdb

**Comment by VaHReX** [comment]
> in this repository, you needn't upload cards.cdb

ok, I uploaded them thinking that since it is the main repository of YGOMobile, and I saw that there were other languages, I created the "es" folder so that Spanish would be included, as I was seeing, the game has an option that is to change the languages to English, I don't know if Korean or Japanese, and Chinese. Maybe in the future Spanish could be added to that list and so users can change the language, of course, what comes after that to achieve it I don't know.

**Comment by fallenstardust** [comment]
so just remove the unrelated files. you can close this pull request and start a new one only with es folder and values

**Pull request closed without merging**
