### PR TITLE
Fix Korean Strings.conf

### PR DESCRIPTION
**Pull request by JSY1728**
-p.m. 10 : 40 (south korea)

### CODE REVIEW

**Comment by fallenstardust** [comment]
ygomobile‘s strings is not all same to ygopro’

**Comment by JSY1728** [comment]
> ygomobile‘s strings is not all same to ygopro’

so, just like to ygopro's strings? (from mycard github) | https://github.com/mycard/ygopro-database

**Comment by fallenstardust** [comment]
you'd better compare with them, some "!system" are different

**Comment by JSY1728** [comment]
> you'd better compare with them, some "!system" are different

I change to
!system 1379 启用扩展卡包调试（下次决斗生效） | 확장 카드 패키지 사용 (다음 듀얼에서 유효)
!system 1380 人机模式（双方无禁限） | AI 모드 (둘 다 제한 없음)
!system 1381 残局模式（含教学局） | 퍼즐 모드 (모든 교육 포함)
!system 1385 此模式人机尚未实装 | 이 모드는 아직 구현되지 않았습니다.

**Comment by JSY1728** [comment]
any other problems?

**Comment by JSY1728** [comment]
I re-fixed korean strings.conf

**Comment by JSY1728** [comment]
> you'd better compare with them, some "!system" are different

any others problem?

**Comment by fallenstardust** [comment]
notice：the3.10.0 new upgrade only can be download from webpage：https://www.pgyer.com/ygomobileko.
hope you may get this message and tell your friends and community

**Comment by JSY1728** [comment]
> notice：the3.10.0 new upgrade only can be download from webpage：https://www.pgyer.com/ygomobileko. hope you may get this message and tell your friends and community

Okay. I'll share that.

**Comment by fallenstardust** [comment]
it have to uninstall the 3.9.8， notice them back up decks，it will be restore in 3.10.0 in deck function menu，too.
after install 3.10.0, they will get upgrade on 3.10.0 for now

**Comment by JSY1728** [comment]
> it have to uninstall the 3.9.8， notice them back up decks，it will be restore in 3.10.0 in deck function menu，too. after install 3.10.0, they will get upgrade on 3.10.0 for now

thanks your helpful.

**Pull request merged**
