### PR TITLE
trying fix IA bugs

### PR DESCRIPTION
**Pull request by VaHReX**

### CODE REVIEW

**Comment by fallenstardust** [comment]
wt  IA bug?

**Comment by VaHReX** [comment]
> wt IA bug?

On most occasions when I try to play vs the AI in rock paper scissors the game crashes and closes

**Comment by fallenstardust** [comment]
you found if changing dialog to default will fix this problem? i dont think it will work. i asked users it happens on the device within x86 cpu

**Comment by VaHReX** [comment]
> you found if changing dialog to default will fix this problem? i dont think it will work. i asked users it happens on the device within x86 cpu

Yes, my cpu phone is x86 , and I guess you mentioned it, I remember that I test the game on a x64 cpu emulator and it never crashed. Can't that compatibility bug with x86 cpu devices be solved?

**Comment by fallenstardust** [comment]
it dont work if changing dialog to default.
by the way. i send a re-email to you. pls check.

**Comment by VaHReX** [comment]
> it dont work if changing dialog to default. by the way. i send a re-email to you. pls check.

I change the dialog by default but I haven't how test it until the next update of the game, in the other hand, I don't se the re-email, can you re send it please?

**Pull request closed without merging**
